[package]
name = "match_server"
version = "0.1.0"
edition = "2021"
description = "card backend"
author = "jyto7034"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
