# Simulator 프로젝트 통합 설정
# 환경 변수로 오버라이드 가능: SIMULATOR_SERVERS_MATCH_SERVER_HOST=localhost

[servers]
[servers.auth_server]
host = "127.0.0.1"
port = 8081
use_tls = false

[servers.match_server]
host = "127.0.0.1"
port = 8080
use_tls = false

[servers.dedicated_server]
host = "127.0.0.1"
port = 8082
use_tls = false

[servers.client]
host = "127.0.0.1"
port = 3000

[database]
[database.redis]
host = "127.0.0.1"
port = 6379
db = 0

[logging]
level = "info"
directory = "logs"
filename = "app.log"
max_files = 10

[testing]
timeout_seconds = 30
retry_count = 3
parallel_tests = 4

