# 서버 설정
[server]
bind_address = "0.0.0.0"
port = 8081
log_level = "info" # 로그 레벨

# 로깅 설정
[logging]
directory = "logs"
filename = "app.log"

# 재시도 설정
[retry]
message_max_elapsed_time_ms = 500
message_initial_interval_ms = 10
message_max_interval_ms = 100

# WebSocket 세션 설정
[session]
heartbeat_interval_seconds = 30
heartbeat_timeout = 120
