# 서버 설정
[server]
bind_address = "0.0.0.0"
port = 8080
log_level = "INFO"

# Redis 설정
[redis]
url = "redis://127.0.0.1:6379"

[jwt]
secret = "your-super-secret-and-long-key-that-no-one-knows"

[matchmaking]
tick_interval_seconds = 5
queue_key_prefix = "queue"
game_modes = ["1v1_ranked"]

