# 서버 설정
[server]
bind_address = "0.0.0.0"
port = 8080
log_level = "INFO"

# Redis 설정
[redis]
url = "redis://127.0.0.1:6379"

[jwt]
secret = "your-super-secret-and-long-key-that-no-one-knows"

# 매치메이킹 설정
[matchmaking]
tick_interval_seconds = 5
queue_key_prefix = "queue"

# 게임 모드 목록 (테이블 배열)
# 각 [[matchmaking.game_modes]] 항목이 하나의 게임 모드를 정의합니다.
[[matchmaking.game_modes]]
id = "Normal_1v1"          # 게임 모드의 고유 ID
required_players = 2       # 매칭에 필요한 인원
use_mmr_matching = false   # MMR 기반 매칭 사용 여부 (일반 모드)

# [[matchmaking.game_modes]]
# id = "Ranked_1v1"
# required_players = 2
# use_mmr_matching = true    # 랭크 모드에서는 이 값을 true로 설정