# 서버 설정
[server]
bind_address = "0.0.0.0"
port = 8080
log_level = "info" # 로그 레벨

# 로깅 설정
[logging]
directory = "logs"
filename = "app.log"

# Redis 설정
[redis]
url = "redis://127.0.0.1:6379"
max_reconnect_attempts = 10
initial_reconnect_delay_ms = 1000
max_reconnect_delay_ms = 60000
dedicated_server_key_pattern = "dedicated_server:*"
notification_channel_pattern = "notifications:*"
state_event_channel_pattern = "events:*"
enable_state_events = true

[jwt]
secret = "your-super-secret-and-long-key-that-no-one-knows"

# 매치메이킹 설정
[matchmaking]
tick_interval_seconds = 1
queue_key_prefix = "queue"
heartbeat_interval_seconds = 30
client_timeout_seconds = 120
loading_session_timeout_seconds = 5
max_dedicated_server_retries = 5
dedicated_request_timeout_seconds = 3
allocation_token_ttl_seconds = 20
slow_loading_threshold_seconds = 15

# 블랙리스트 설정
[blacklist]
timeout_threshold = 2
timeout_window_hours = 1
block_duration_minutes = 10
check_ip_change = true
ip_change_strategy = "ReduceByPercent"  # ClearAll, ReduceByPercent, KeepRecent, NoReduction
ip_change_reduction_percent = 50
ip_change_min_violations_to_keep = 1

# 게임 서버 상태 문자열
[server_status]
idle = "idle"

# 게임 모드 목록 (테이블 배열)
# 각 [[matchmaking.game_modes]] 항목이 하나의 게임 모드를 정의합니다.
[[matchmaking.game_modes]]
id = "Normal_1v1"          # 게임 모드의 고유 ID
required_players = 2       # 매칭에 필요한 인원
use_mmr_matching = false   # 일반 모드)

# [[matchmaking.game_modes]]
# id = "Ranked_1v1"
# required_players = 2
# use_mmr_matching = true    # 랭크 모드에서는 이 값을 true로 설정
